"""Batch, source-bound graph extraction for Research Graph producers."""

from __future__ import annotations

import json
import logging
from collections.abc import Iterable
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from langchain_core.messages import HumanMessage

from open_deep_research.budget import (
    budget_from_model_response,
    estimate_tokens,
    merge_budget_usage,
    truncate_text_to_token_budget,
)
from open_deep_research.observability import observe_model_ainvoke
from open_deep_research.research_graph.models import (
    Claim,
    Coverage,
    Entity,
    Event,
    Evidence,
    Finding,
    GraphEdge,
    GraphExtractionOutput,
    GraphNode,
    RawResearchDocument,
    ResearchDeltaGraph,
    ResearchGraphScope,
    Source,
    SourceFinding,
    Uncertainty,
)
from open_deep_research.research_graph.schema import (
    content_hash,
    normalize_text,
    stable_id,
)

LOGGER = logging.getLogger(__name__)


@dataclass
class ExtractionBatchResult:
    """One LLM extraction batch and its normalized graph delta."""

    delta: ResearchDeltaGraph
    budget_usage: dict[str, Any] = field(default_factory=dict)
    input_tokens: int | None = None
    output_tokens: int | None = None
    input_token_quality: str = "unavailable"
    output_token_quality: str = "unavailable"


@dataclass
class ExtractionResult:
    """Aggregate extraction result for a tool batch."""

    batches: list[ExtractionBatchResult] = field(default_factory=list)
    skipped_documents: list[str] = field(default_factory=list)
    budget_usage: dict[str, Any] = field(default_factory=dict)

    @property
    def deltas(self) -> list[ResearchDeltaGraph]:
        """Return normalized deltas for callers that do not need metrics."""
        return [batch.delta for batch in self.batches]


class GraphExtractionError(RuntimeError):
    """Raised when a graph extraction response cannot be normalized safely."""


def batch_documents_by_tokens(
    documents: Iterable[RawResearchDocument],
    max_tokens: int,
) -> list[list[RawResearchDocument]]:
    """Group source documents by estimated tokens without crossing the budget.

    A single over-sized source is truncated for extraction only.  Its full
    content hash remains on the source node, so changing content is still
    detected on the next retrieval.
    """
    limit = max(1, int(max_tokens))
    batches: list[list[RawResearchDocument]] = []
    current: list[RawResearchDocument] = []
    current_tokens = 0
    for document in documents:
        source_tokens = max(1, estimate_tokens(document.content))
        candidate = document
        if source_tokens > limit:
            truncated, _ = truncate_text_to_token_budget(document.content, limit)
            candidate = document.model_copy(
                update={
                    "content": truncated,
                    "metadata": {
                        **document.metadata,
                        "content_truncated_for_extraction": True,
                    },
                }
            )
            source_tokens = max(1, estimate_tokens(candidate.content))
        if current and current_tokens + source_tokens > limit:
            batches.append(current)
            current = []
            current_tokens = 0
        current.append(candidate)
        current_tokens += source_tokens
    if current:
        batches.append(current)
    return batches


def build_source_documents_from_raw_result(
    *,
    run_id: str,
    role: str,
    research_round: int,
    task_id: str,
    tool_name: str,
    tool_call_id: str,
    args: Any,
    observation: Any,
) -> list[RawResearchDocument]:
    """Convert a raw tool result into source-bound documents.

    URLs are extracted from the tool payload, never generated by the LLM.  The
    dedicated Tavily raw path returns a JSON envelope with one item per URL;
    other tools receive one deterministic synthetic source when no URL is
    available.
    """
    if not observation or tool_name in {"think_tool", "ResearchComplete"}:
        return []
    decoded = observation
    if isinstance(observation, str):
        try:
            decoded = json.loads(observation)
        except (TypeError, ValueError):
            decoded = observation

    documents: list[RawResearchDocument] = []
    if isinstance(decoded, dict) and decoded.get("type") == "research_raw_search":
        raw_results = decoded.get("results") or []
        for index, item in enumerate(raw_results):
            if not isinstance(item, dict):
                continue
            url = _safe_text(item.get("url")) or None
            title = _safe_text(item.get("title"))
            content = _safe_text(item.get("raw_content") or item.get("content"))
            if not content:
                continue
            source_key = url or f"{tool_call_id}:{index}"
            source_id = stable_id("SRC", run_id, role, tool_call_id, source_key)
            documents.append(
                RawResearchDocument(
                    source_id=source_id,
                    url=url,
                    source_path=url,
                    title=title,
                    content=content,
                    source_type=_safe_text(item.get("source_type")) or "web_search",
                    tool_name=tool_name,
                    query=_safe_text(item.get("query")) or _args_query(args),
                    published_at=_safe_text(item.get("published_at")) or None,
                    retrieved_at=_safe_text(item.get("retrieved_at")) or _now(),
                    content_hash=content_hash(content),
                    metadata={
                        "tool_call_id": tool_call_id,
                        "result_index": index,
                        "raw_result": True,
                    },
                )
            )
        return documents

    text = _safe_text(decoded)
    if not text:
        return []
    urls = _extract_urls(decoded)
    if urls:
        for index, url in enumerate(urls):
            source_id = stable_id("SRC", run_id, role, tool_call_id, url)
            documents.append(
                RawResearchDocument(
                    source_id=source_id,
                    url=url,
                    source_path=url,
                    title=f"{tool_name} result {index + 1}",
                    content=text,
                    source_type=tool_name,
                    tool_name=tool_name,
                    query=_args_query(args),
                    retrieved_at=_now(),
                    content_hash=content_hash(text),
                    metadata={"tool_call_id": tool_call_id, "result_index": index},
                )
            )
        return documents

    source_id = stable_id("SRC", run_id, role, tool_call_id, tool_name)
    documents.append(
        RawResearchDocument(
            source_id=source_id,
            source_path=f"tool://{tool_name}/{tool_call_id}",
            title=f"{tool_name} result",
            content=text,
            source_type=tool_name,
            tool_name=tool_name,
            query=_args_query(args),
            retrieved_at=_now(),
            content_hash=content_hash(text),
            metadata={"tool_call_id": tool_call_id},
        )
    )
    return documents


class GraphExtractor:
    """One structured LLM call per token-aware source batch."""

    def __init__(
        self,
        *,
        model: Any,
        model_name: str,
        max_tokens: int,
        max_retries: int = 3,
        batch_token_limit: int = 12_000,
    ) -> None:
        """Configure one structured extraction model for token-aware batches."""
        self.model = model
        self.model_name = model_name
        self.max_tokens = max_tokens
        self.max_retries = max_retries
        self.batch_token_limit = batch_token_limit

    async def extract(
        self,
        documents: Iterable[RawResearchDocument],
        *,
        scope: ResearchGraphScope,
    ) -> ExtractionResult:
        """Extract a related delta graph from all supplied documents."""
        normalized_documents = [
            document
            if document.content_hash
            else document.model_copy(update={"content_hash": content_hash(document.content)})
            for document in documents
        ]
        result = ExtractionResult()
        for batch in batch_documents_by_tokens(normalized_documents, self.batch_token_limit):
            batch_result = await self._extract_batch(batch, scope=scope)
            result.batches.append(batch_result)
            result.budget_usage = merge_budget_usage(result.budget_usage, batch_result.budget_usage)
        return result

    async def _extract_batch(
        self,
        documents: list[RawResearchDocument],
        *,
        scope: ResearchGraphScope,
    ) -> ExtractionBatchResult:
        prompt = _build_extraction_prompt(documents, scope)
        model = self.model
        if hasattr(model, "with_structured_output"):
            model = model.with_structured_output(GraphExtractionOutput)
        if hasattr(model, "with_retry"):
            model = model.with_retry(stop_after_attempt=self.max_retries)
        response = await observe_model_ainvoke(
            model,
            [HumanMessage(content=prompt)],
            observer_model=self.model_name,
            observer_structured_output=True,
            observer_component="graph_extraction",
        )
        budget_usage = budget_from_model_response(response)
        output = _coerce_extraction_output(response)
        delta = normalize_extraction_output(output, documents, scope=scope)
        input_tokens = _usage_token(budget_usage, "input_tokens")
        output_tokens = _usage_token(budget_usage, "output_tokens")
        return ExtractionBatchResult(
            delta=delta,
            budget_usage=budget_usage,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            input_token_quality="exact" if input_tokens else "unavailable",
            output_token_quality="exact" if output_tokens else "unavailable",
        )


def normalize_extraction_output(
    output: GraphExtractionOutput | dict[str, Any],
    documents: list[RawResearchDocument],
    *,
    scope: ResearchGraphScope,
) -> ResearchDeltaGraph:
    """Bind semantic extraction output to code-owned source metadata and IDs."""
    parsed = output if isinstance(output, GraphExtractionOutput) else GraphExtractionOutput.model_validate(output)
    source_by_id = {document.source_id: document for document in documents}
    source_by_url = {document.url: document for document in documents if document.url}
    delta = ResearchDeltaGraph(scope=scope)
    # Source IDs are code-owned and can be used as endpoints of explicit LLM
    # relation records, but their metadata is never taken from the LLM output.
    local_to_id: dict[str, str] = {
        document.source_id: document.source_id for document in documents
    }
    delta.sources = [
        Source(
            source_id=document.source_id,
            run_id=scope.run_id,
            url=document.url,
            source_path=document.source_path,
            title=document.title,
            source_type=document.source_type,
            tool_name=document.tool_name,
            query=document.query,
            published_at=document.published_at,
            retrieved_at=document.retrieved_at,
            content_hash=document.content_hash or content_hash(document.content),
            role=scope.role,
            research_round=scope.research_round,
            task_id=scope.task_id,
            metadata=document.metadata,
        )
        for document in documents
    ]

    claim_records: list[tuple[dict[str, Any], Claim]] = []
    for index, raw in enumerate(parsed.claims):
        statement = _first_text(raw, "statement", "text", "claim", "summary")
        if not statement:
            continue
        local_ref = _first_text(raw, "local_id", "ref", "claim_ref", "claim_id") or f"claim_{index + 1}"
        claim_id = stable_id("CLM", scope.run_id, normalize_text(statement))
        local_to_id[local_ref] = claim_id
        claim = Claim(
            claim_id=claim_id,
            run_id=scope.run_id,
            statement=statement,
            status=_claim_status(raw.get("status")),
            confidence=_confidence(raw.get("confidence")),
            role=scope.role,
            research_round=scope.research_round,
            task_id=scope.task_id,
        )
        claim_records.append((raw, claim))
        if not any(existing.claim_id == claim_id for existing in delta.claims):
            delta.claims.append(claim)

    for index, raw in enumerate(parsed.evidences):
        statement = _first_text(raw, "statement", "text", "evidence", "summary")
        if not statement:
            continue
        source = _resolve_source(raw, source_by_id, source_by_url, documents)
        if source is None:
            LOGGER.warning("Dropping extracted evidence with unknown source reference.")
            continue
        local_ref = _first_text(raw, "local_id", "ref", "evidence_ref", "evidence_id") or f"evidence_{index + 1}"
        evidence_id = stable_id("EVD", scope.run_id, source.source_id, normalize_text(statement))
        local_to_id[local_ref] = evidence_id
        evidence = Evidence(
            evidence_id=evidence_id,
            run_id=scope.run_id,
            source_id=source.source_id,
            statement=statement,
            evidence_type=_first_text(raw, "evidence_type", "type") or "fact",
            stance=_stance(raw.get("stance")),
            confidence=_confidence(raw.get("confidence")),
            quote=_first_text(raw, "quote", "excerpt"),
            role=scope.role,
            research_round=scope.research_round,
            task_id=scope.task_id,
            supports_claim_ids=_map_refs(raw, ("supports_claim_ids", "supports_claims", "claim_ids"), local_to_id),
            contradicts_claim_ids=_map_refs(raw, ("contradicts_claim_ids", "contradicts_claims"), local_to_id),
            contextualizes_claim_ids=_map_refs(raw, ("contextualizes_claim_ids", "contextualizes_claims"), local_to_id),
        )
        if not any(existing.evidence_id == evidence_id for existing in delta.evidences):
            delta.evidences.append(evidence)

    for index, raw in enumerate(parsed.source_findings):
        summary = _first_text(raw, "summary", "statement", "text")
        source = _resolve_source(raw, source_by_id, source_by_url, documents)
        if not summary or source is None:
            continue
        local_ref = _first_text(raw, "local_id", "ref", "source_finding_id") or f"source_finding_{index + 1}"
        item_id = stable_id("SFD", scope.run_id, source.source_id, normalize_text(summary))
        local_to_id[local_ref] = item_id
        delta.source_findings.append(
            SourceFinding(
                source_finding_id=item_id,
                run_id=scope.run_id,
                source_id=source.source_id,
                summary=summary,
                evidence_ids=_map_refs(raw, ("evidence_ids", "evidence_refs"), local_to_id),
                claim_ids=_map_refs(raw, ("claim_ids", "claim_refs"), local_to_id),
                confidence=_confidence(raw.get("confidence")),
            )
        )

    for index, raw in enumerate(parsed.entities):
        name = _first_text(raw, "name", "entity", "label")
        if not name:
            continue
        local_ref = _first_text(raw, "local_id", "ref", "entity_ref", "entity_id") or f"entity_{index + 1}"
        entity_id = stable_id("ENT", scope.run_id, normalize_text(name), _first_text(raw, "entity_type", "type"))
        local_to_id[local_ref] = entity_id
        delta.entities.append(
            Entity(
                entity_id=entity_id,
                run_id=scope.run_id,
                name=name,
                entity_type=_first_text(raw, "entity_type", "type") or "Entity",
                aliases=_text_list(raw.get("aliases")),
                evidence_ids=_map_refs(raw, ("evidence_ids", "evidence_refs"), local_to_id),
            )
        )

    for index, raw in enumerate(parsed.events):
        name = _first_text(raw, "name", "event", "statement", "summary")
        if not name:
            continue
        local_ref = _first_text(raw, "local_id", "ref", "event_ref", "event_id") or f"event_{index + 1}"
        event_id = stable_id("EVT", scope.run_id, normalize_text(name), _first_text(raw, "date", "event_date"))
        local_to_id[local_ref] = event_id
        delta.events.append(
            Event(
                event_id=event_id,
                run_id=scope.run_id,
                name=name,
                date=_first_text(raw, "date", "event_date") or None,
                description=_first_text(raw, "description", "summary"),
                evidence_ids=_map_refs(raw, ("evidence_ids", "evidence_refs"), local_to_id),
                entity_ids=_map_refs(raw, ("entity_ids", "entity_refs"), local_to_id),
            )
        )

    # Resolve claim-to-event/entity links after both endpoint collections have
    # been assigned deterministic IDs.
    for raw, claim in claim_records:
        event_ids = _map_refs(raw, ("event_ids", "event_refs"), local_to_id)
        entity_ids = _map_refs(raw, ("entity_ids", "entity_refs"), local_to_id)
        if event_ids or entity_ids:
            for index, existing in enumerate(delta.claims):
                if existing.claim_id == claim.claim_id:
                    delta.claims[index] = existing.model_copy(
                        update={"event_ids": event_ids, "entity_ids": entity_ids}
                    )
                    break

    for index, raw in enumerate(parsed.uncertainties):
        summary = _first_text(raw, "summary", "statement", "text")
        if not summary:
            continue
        claim_ids = _map_refs(raw, ("claim_ids", "claim_refs"), local_to_id)
        evidence_ids = _map_refs(raw, ("evidence_ids", "evidence_refs"), local_to_id)
        uncertainty_id = stable_id("UNT", scope.run_id, normalize_text(summary), *claim_ids, *evidence_ids)
        local_ref = _first_text(raw, "local_id", "ref", "uncertainty_ref", "uncertainty_id") or f"uncertainty_{index + 1}"
        local_to_id[local_ref] = uncertainty_id
        delta.uncertainties.append(
            Uncertainty(
                uncertainty_id=uncertainty_id,
                run_id=scope.run_id,
                summary=summary,
                claim_ids=claim_ids,
                evidence_ids=evidence_ids,
                source_ids=_map_source_refs(raw, source_by_id, source_by_url, documents),
                severity=_severity(raw.get("severity")),
            )
        )

    for index, raw in enumerate(parsed.findings):
        summary = _first_text(raw, "summary", "statement", "finding", "text")
        if not summary:
            continue
        claim_ids = _map_refs(raw, ("claim_ids", "claim_refs"), local_to_id)
        evidence_ids = _map_refs(raw, ("evidence_ids", "evidence_refs"), local_to_id)
        uncertainty_ids = _map_refs(raw, ("uncertainty_ids", "uncertainty_refs"), local_to_id)
        finding_id = stable_id("FND", scope.run_id, normalize_text(summary), *claim_ids, *evidence_ids)
        local_ref = _first_text(raw, "local_id", "ref", "finding_ref", "finding_id") or f"finding_{index + 1}"
        local_to_id[local_ref] = finding_id
        delta.findings.append(
            Finding(
                finding_id=finding_id,
                run_id=scope.run_id,
                summary=summary,
                claim_ids=claim_ids,
                evidence_ids=evidence_ids,
                uncertainty_ids=uncertainty_ids,
                confidence=_confidence(raw.get("confidence")),
                finding_type=_first_text(raw, "finding_type", "type") or "research_finding",
            )
        )

    for index, raw in enumerate(parsed.coverages):
        summary = _first_text(raw, "summary", "statement", "text")
        if not summary:
            continue
        coverage_id = stable_id("COV", scope.run_id, scope.task_id, normalize_text(summary))
        local_ref = _first_text(raw, "local_id", "ref", "coverage_ref", "coverage_id") or f"coverage_{index + 1}"
        local_to_id[local_ref] = coverage_id
        delta.coverages.append(
            Coverage(
                coverage_id=coverage_id,
                run_id=scope.run_id,
                task_id=scope.task_id,
                status=_coverage_status(raw.get("status")),
                summary=summary,
                finding_ids=_map_refs(raw, ("finding_ids", "finding_refs"), local_to_id),
                claim_ids=_map_refs(raw, ("claim_ids", "claim_refs"), local_to_id),
                evidence_ids=_map_refs(raw, ("evidence_ids", "evidence_refs"), local_to_id),
            )
        )

    if not delta.coverages and (delta.evidences or delta.claims or delta.findings):
        # This is structural batch coverage, not a final research-complete
        # judgment.  Research Review/Context Manager owns the semantic gap
        # decision, while the graph still records what task received material.
        delta.coverages.append(
            Coverage(
                coverage_id=stable_id(
                    "COV",
                    scope.run_id,
                    scope.task_id,
                    "batch",
                    len(delta.evidences),
                    len(delta.claims),
                ),
                run_id=scope.run_id,
                task_id=scope.task_id,
                status="partial",
                summary="This extraction batch produced material linked to the current research task.",
                finding_ids=[finding.finding_id for finding in delta.findings],
                claim_ids=[claim.claim_id for claim in delta.claims],
                evidence_ids=[evidence.evidence_id for evidence in delta.evidences],
            )
        )

    # Add the run/task anchors in code so Coverage can always be traversed back
    # to the current task even when the LLM emits no explicit coverage object.
    run_node_id = stable_id("RUN", scope.run_id)
    task_node_id = stable_id("TASK", scope.run_id, scope.task_id)
    delta.nodes.extend(
        [
            GraphNode(
                node_id=run_node_id,
                node_type="ResearchRun",
                run_id=scope.run_id,
                role=scope.role,
                research_round=scope.research_round,
                task_id=scope.task_id,
                properties={"run_id": scope.run_id},
            ),
            GraphNode(
                node_id=task_node_id,
                node_type="ResearchTask",
                run_id=scope.run_id,
                role=scope.role,
                research_round=scope.research_round,
                task_id=scope.task_id,
                properties={"task_id": scope.task_id, "role": scope.role},
            ),
        ]
    )
    for coverage in delta.coverages:
        delta.edges.append(
            GraphEdge(
                edge_id=stable_id("EDG", "ASSESSES", coverage.coverage_id, task_node_id),
                relation_type="ASSESSES",
                source_id=coverage.coverage_id,
                target_id=task_node_id,
                run_id=scope.run_id,
            )
        )
    for raw in parsed.relations:
        relation = _first_text(raw, "relation_type", "relationship", "type").upper()
        if relation not in {
            "EXTRACTED_FROM",
            "SUPPORTS",
            "CONTRADICTS",
            "CONTEXTUALIZES",
            "FROM_SOURCE",
            "DERIVED_FROM",
            "ABOUT_CLAIM",
            "RELATES_TO",
            "INVOLVES",
            "APPLIES_TO",
            "BASED_ON",
            "SUPPORTED_BY",
            "ASSESSES",
        }:
            continue
        source_id = _resolve_ref(_first_text(raw, "source_id", "source_ref", "from"), local_to_id)
        target_id = _resolve_ref(_first_text(raw, "target_id", "target_ref", "to"), local_to_id)
        if not source_id or not target_id:
            continue
        delta.edges.append(
            GraphEdge(
                edge_id=stable_id("EDG", relation, source_id, target_id),
                relation_type=relation,  # type: ignore[arg-type]
                source_id=source_id,
                target_id=target_id,
                run_id=scope.run_id,
                properties={"extracted_relation": True},
            )
        )
    return delta


def _build_extraction_prompt(
    documents: list[RawResearchDocument],
    scope: ResearchGraphScope,
) -> str:
    payload = [
        {
            "source_id": document.source_id,
            "title": document.title,
            "source_type": document.source_type,
            "query": document.query,
            "content": document.content,
        }
        for document in documents
    ]
    return (
        "You are the Research Graph extraction component, not the final analyst. "
        "Extract only semantic evidence from this batch of new research material. "
        "Do not call tools, make a final risk judgment, schedule follow-up work, "
        "or invent URLs/source metadata. Every evidence item must reference one of "
        "the supplied source_id values. Keep provenance IDs as local refs; code will "
        "assign stable graph IDs. Distinguish facts, allegations, interpretations, "
        "recommendations, and uncertainty. Build one related graph delta with claims, "
        "events, entities, source findings, uncertainties, and findings where supported.\n\n"
        f"Scope: {scope.model_dump_json()}\n"
        "Allowed source registry and material:\n"
        f"{json.dumps(payload, ensure_ascii=False)}\n\n"
        "Return structured output using the GraphExtractionOutput schema."
    )


def _coerce_extraction_output(response: Any) -> GraphExtractionOutput:
    if isinstance(response, GraphExtractionOutput):
        return response
    if isinstance(response, dict):
        return GraphExtractionOutput.model_validate(response)
    model_dump = getattr(response, "model_dump", None)
    if callable(model_dump):
        return GraphExtractionOutput.model_validate(model_dump())
    raise GraphExtractionError("Graph extraction model returned an invalid structured output.")


def _resolve_source(
    raw: dict[str, Any],
    source_by_id: dict[str, RawResearchDocument],
    source_by_url: dict[str | None, RawResearchDocument],
    documents: list[RawResearchDocument],
) -> RawResearchDocument | None:
    reference = _first_text(raw, "source_id", "source_ref", "source", "url")
    if reference in source_by_id:
        return source_by_id[reference]
    if reference in source_by_url:
        return source_by_url[reference]
    if not reference and len(documents) == 1:
        return documents[0]
    return None


def _resolve_ref(reference: str, local_to_id: dict[str, str]) -> str:
    if not reference:
        return ""
    if reference in local_to_id:
        return local_to_id[reference]
    return reference if reference in set(local_to_id.values()) else ""


def _map_refs(raw: dict[str, Any], keys: tuple[str, ...], mapping: dict[str, str]) -> list[str]:
    for key in keys:
        if key in raw:
            values = raw.get(key)
            if isinstance(values, str):
                values = [values]
            if isinstance(values, list):
                return [resolved for value in values if (resolved := _resolve_ref(str(value), mapping))]
    return []


def _map_source_refs(
    raw: dict[str, Any],
    source_by_id: dict[str, RawResearchDocument],
    source_by_url: dict[str | None, RawResearchDocument],
    documents: list[RawResearchDocument],
) -> list[str]:
    refs = raw.get("source_ids") or raw.get("source_refs") or raw.get("sources") or []
    if isinstance(refs, str):
        refs = [refs]
    result = []
    for ref in refs if isinstance(refs, list) else []:
        source = _resolve_source({"source_id": str(ref)}, source_by_id, source_by_url, documents)
        if source is not None and source.source_id not in result:
            result.append(source.source_id)
    return result


def _first_text(raw: dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = raw.get(key)
        if value is not None and str(value).strip():
            return str(value).strip()
    return ""


def _safe_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    try:
        return json.dumps(value, ensure_ascii=False, default=str)
    except (TypeError, ValueError):
        return str(value)


def _text_list(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value.strip()] if value.strip() else []
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    return []


def _extract_urls(value: Any) -> list[str]:
    text = _safe_text(value)
    candidates = []
    for part in text.replace('"', " ").replace("'", " ").split():
        candidate = part.rstrip(",.;)]}")
        if candidate.startswith(("http://", "https://")) and candidate not in candidates:
            candidates.append(candidate)
    return candidates


def _args_query(args: Any) -> str:
    if not isinstance(args, dict):
        return ""
    query = args.get("queries") or args.get("query")
    if isinstance(query, list):
        return ", ".join(str(item) for item in query)
    return str(query or "")


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _confidence(value: Any) -> float | None:
    try:
        if value is None or str(value).strip() == "":
            return None
        return max(0.0, min(1.0, float(value)))
    except (TypeError, ValueError):
        return None


def _claim_status(value: Any) -> str:
    normalized = normalize_text(value)
    return normalized if normalized in {"confirmed", "disputed", "unsupported", "open", "unknown"} else "open"


def _stance(value: Any) -> str:
    normalized = normalize_text(value)
    return normalized if normalized in {"supports", "contradicts", "neutral", "unknown"} else "unknown"


def _severity(value: Any) -> str:
    normalized = normalize_text(value)
    return normalized if normalized in {"low", "medium", "high", "unknown"} else "unknown"


def _coverage_status(value: Any) -> str:
    normalized = normalize_text(value)
    return normalized if normalized in {"covered", "partial", "open", "unknown"} else "unknown"


def _usage_token(usage: dict[str, Any], key: str) -> int | None:
    value = usage.get(key)
    return int(value) if isinstance(value, int) and value > 0 else None


__all__ = [
    "ExtractionBatchResult",
    "ExtractionResult",
    "GraphExtractionError",
    "GraphExtractor",
    "batch_documents_by_tokens",
    "build_source_documents_from_raw_result",
    "normalize_extraction_output",
]
